# Do not edit. Generated by the configure script.
export PATH:=/home/ashuu/Desktop/projects/bank_project/bankenv/src/node-v19.2.0/out/tools/bin:$(PATH)
BUILDTYPE=Release
NODE_TARGET_TYPE=executable
PYTHON=/usr/bin/python3.10
PREFIX=/home/ashuu/Desktop/projects/bank_project/bankenv
